[nfs]
172.31.95.61 ansible_ssh_user='ec2-user'

[webservers]
172.31.94.138 ansible_ssh_user='ec2-user'
172.31.93.227 ansible_ssh_user='ec2-user'

[db]
172.31.82.122 ansible_ssh_user='ec2-user' 

[lb]
172.31.24.52 ansible_ssh_user='ubuntu'