  pipeline {
    agent any

 stages {
   stage("Initial Cleanup") {
         steps {
           dir("${WORKSPACE}") {
             deleteDir()
           }
         }
       }
     
   stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }

    stage('Package') {
      steps {
        script {
          sh 'echo "Packaging App"'
        }
      }
    }

    stage('Deploying') {
      steps {
        script {
          sh 'echo "Deploying to Dev"'
        }
      }
    }
   
    stage("clean up") {
      steps {
        cleanWs()
      }
    }
   }
   
   
}
