---
- hosts: nginx
- name: install nginx
  ansible.builtin.import_playbook: ../static-assignments/nginx.yml

- hosts: db
- name: database assignment
  ansible.builtin.import_playbook: ../static-assignments/database.yml

