---
# - hosts: artifactory
# - name: artifactory assignment
#  ansible.builtin.import_playbook: ../static-assignments/artifactory.yml

# - hosts: nginx
# - name: install nginx
#  ansible.builtin.import_playbook: ../static-assignments/nginx.yml

# - hosts: db
# - name: database assignment
#  ansible.builtin.import_playbook: ../static-assignments/database.yml

- hosts: todo
- name: Deploy the todo application
  ansible.builtin.import_playbook: ../static-assignments/deployment.yml
