---
# tasks file for artifactory

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install package
  ansible.builtin.package:
    name: jfrog-artifactory-{{ artifactory_flavour }}
    state: present

- name: ensure artifactory_file_store_dir exists
  ansible.builtin.file:
    path: "{{ artifactory_file_store_dir }}"
    state: directory
    mode: "0755"
    owner: artifactory
    group: artifactory

- name: configure artifactory
  ansible.builtin.template:
    src: binarystore.xml.j2
    dest: "{{ artifactory_home }}/binarystore.xml"
    mode: "0644"
    owner: artifactory
    group: artifactory
  notify:
    - restart artifactory

- name: set ownership for artifactory_logs
  ansible.builtin.file:
    path: "{{ artifactory_logs }}"
    state: directory
    mode: "0755"
    owner: artifactory
    group: artifactory

- name: start and enable artifactory
  ansible.builtin.service:
    name: artifactory
    state: started
    enabled: yes
