---
# tasks file for artifactory

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install java 11
  ansible.builtin.yum:
    name: java-11-openjdk-devel
    state: present

- name: install java 11
  ansible.builtin.yum:
    name: 
      - wget
      - unzip
    state: present

- name: configure artifactory
  ansible.builtin.template:
    src: templates/bash-profile.j2
    dest: .bash_profile
    mode: "0644"
    owner: artifactory
    group: artifactory
  notify:
    - restart artifactory

- name: reload the /etc/profile
  shell: source ~/.bash_profile

- name: add the repository key to repos list
  ansible.builtin.get_url:
    url:  https://releases.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo 
    dest: /home/ec2-user/jfrog-artifactory-rpms.repo
    mode: '0755'
 
- name: Copy the downloaded file to the etc repo
  ansible.builtin.copy:
    src: /home/ec2-user/jfrog-artifactory-rpms.repo
    dest: /etc/yum.repos.d/jfrog-artifactory-rpms.repo
    remote_src: yes
    follow: yes

- name: set ownership for artifactory_logs
  ansible.builtin.file:
    path: "{{ artifactory_logs }}"
    state: directory
    mode: "0755"
    owner: artifactory
    group: artifactory

- name: start and enable artifactory
  ansible.builtin.service:
    name: artifactory
    state: started
    enabled: yes
